name: bird_instructor
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.0.0
  web_socket_channel: ^2.4.0
  record: ^5.1.2
  audioplayers: ^6.4.0
  mic_stream: ^0.7.2
  path_provider: ^2.1.1
  # base64: ^2.3.3
  http: ^1.1.0
  audio_waveforms: ^1.3.0
  intl: ^0.20.2
  flutter_svg: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/InterVariable.ttf
          style: normal
        - asset: assets/fonts/InterVariable-Italic.ttf
          style: italic


  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

